<?php
# Selenium test suite for SMS – V1.0_Original_SMS
# Generated by Sivaranjei T., 2026, University of Colombo, Sri Lanka.
require_once __DIR__ . '/../../../vendor/autoload.php';

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverExpectedCondition;
use Facebook\WebDriver\WebDriverWait;
use Facebook\WebDriver\WebDriverDimension;

class SchoolManagementSystemTest
{
    private $driver;
    private $baseUrl = 'http://localhost/research/sms/V1.0_Original_SMS/';

    public function setUp(): void
    {
        $host = 'http://localhost:60554'; // Change this if ChromeDriver runs on another port

        $options = new ChromeOptions();
        $options->setBinary('C:\Program Files\Google\Chrome\Application\chrome.exe');
        $options->addArguments(['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--window-size=1920,1080']);

        $capabilities = DesiredCapabilities::chrome();
        $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

        $this->driver = RemoteWebDriver::create($host, $capabilities);
        $this->driver->manage()->window()->maximize();
    }

    public function tearDown(): void
    {
        if ($this->driver) {
            $this->driver->quit();
        }
    }

    private function waitForLoginModal(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('loginFrom')));
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('email')));
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('password')));
        $wait->until(WebDriverExpectedCondition::elementToBeClickable(WebDriverBy::id('btnSubmit')));
    }

    private function clickElementWhenReady(WebDriverBy $locator): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::elementToBeClickable($locator));
        $element = $this->driver->findElement($locator);

        try {
            $element->click();
        } catch (Exception $e) {
            $this->driver->executeScript('arguments[0].click();', [$element]);
        }
    }

    private function loginAs(string $email, string $password): void
    {
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        $emailElement = $this->driver->findElement(WebDriverBy::id('email'));
        $passwordElement = $this->driver->findElement(WebDriverBy::id('password'));

        $emailElement->clear()->sendKeys($email);
        $passwordElement->clear()->sendKeys($password);

        sleep(2);
        $this->clickElementWhenReady(WebDriverBy::id('btnSubmit'));
    }

    private function waitForSignOutLink(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::cssSelector('.dropdown.user.user-menu > a.dropdown-toggle')));
    }

    private function openUserMenu(): void
    {
        $this->clickElementWhenReady(WebDriverBy::cssSelector('.dropdown.user.user-menu > a.dropdown-toggle'));
    }

    private function clickSignOut(): void
    {
        $this->openUserMenu();
        sleep(2);
        $this->clickElementWhenReady(WebDriverBy::xpath("//a[normalize-space(text())='Sign out']"));
    }

    private function waitForDashboardHeading(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//section[contains(@class,'content-header')]//h1[contains(normalize-space(.),'Dashboard') or contains(normalize-space(.),'Dashboard')]")));
    }

    private function waitForDashboardInfoBox(string $text): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//span[contains(@class,'info-box-text') and normalize-space(text())='$text']")));
    }

    private function goToClassroomPage(): void
    {
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->clickElementWhenReady(WebDriverBy::cssSelector('a[href="class_room.php"]'));
        $this->waitForClassroomPage();
    }

    private function waitForClassroomPage(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/class_room.php'));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//h1[contains(normalize-space(.),'Classroom')]") ));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('example1')));
    }

    private function waitForClassroomRow(string $name): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]")));
    }

    private function waitForClassroomNoRow(string $name): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(function () use ($name) {
            $rows = $this->driver->findElements(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]"));
            return count($rows) === 0;
        });
    }

    private function clickEditClassroomByName(string $name): void
    {
        $this->clickElementWhenReady(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]//a[contains(normalize-space(.),'Edit')]"));
    }

    private function deleteClassroomByName(string $name): void
    {
        $this->clickElementWhenReady(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]//a[contains(@class,'confirm-delete')]"));
        $this->clickElementWhenReady(WebDriverBy::id('btnYes'));
        $this->waitForClassroomNoRow($name);
    }

    private function createUniqueClassroomName(): string
    {
        return 'CR_' . time() . '_' . rand(1000, 9999);
    }

    private function waitForModalVisible(string $modalId): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id($modalId)));
    }

    private function waitForModalHidden(string $modalId): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::invisibilityOfElementLocated(WebDriverBy::id($modalId)));
    }

    private function verifySidebarItems(array $items): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        foreach ($items as $item) {
            $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(
                WebDriverBy::xpath("//span[contains(normalize-space(text()),'{$item}')]")
            ));
        }
    }

    private function navigateToMenuPage(string $pageLink): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::elementToBeClickable(WebDriverBy::cssSelector("a[href='{$pageLink}']")));
        $this->clickElementWhenReady(WebDriverBy::cssSelector("a[href='{$pageLink}']"));
        sleep(2);
    }
    private function clickTreeviewLink(string $treeviewSpanText, string $submenuLink): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        // Find and click the treeview header
        $this->clickElementWhenReady(WebDriverBy::xpath("//span[normalize-space(text())='{$treeviewSpanText}']/parent::a"));
        sleep(1);
        // Then click the submenu link
        $this->clickElementWhenReady(WebDriverBy::cssSelector("a[href='{$submenuLink}']"));
        sleep(2);
    }
    private function verifyPageLoaded(string $pageTitle): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(
            WebDriverBy::xpath("//h1[contains(normalize-space(text()),'{$pageTitle}')] | //section[contains(@class,'content-header')]//h1")
        ));
    }

    public function testLoginPageDisplays(): void
    {
        echo "Running testLoginPageDisplays...\n";
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        sleep(2);
        echo "✓ Test Case 1: Login page and modal displayed\n";
    }

    public function testInvalidLogin(): void
    {
        echo "Running testInvalidLogin...\n";
        $this->loginAs('invalid@example.com', 'wrongpass');

        $wait = new WebDriverWait($this->driver, 20);
        try {
            $wait->until(WebDriverExpectedCondition::urlContains('view/login.php?do=login_error'));
            echo "Test Case 2: Invalid login redirects to error page\n";
        } catch (Exception $e) {
            $wait->until(WebDriverExpectedCondition::urlContains('view/login.php'));
            echo "✓ Test Case 2: Invalid login stays on login page\n";
        }

        sleep(2);
    }

    public function testAdminLoginAndAccess(): void
    {
        echo "Running testAdminLoginAndAccess...\n";
        $this->loginAs('admin@getprojects.org', 'Admin12345');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->waitForDashboardInfoBox('Total Student');

        echo "✓ Test Case 3: Admin dashboard loaded\n";
        sleep(1);

         // Verify sidebar items for Admin role
        $this->verifySidebarItems(['Dashboard', 'My Profile']);
        sleep(1);
        echo "✓ Test Case 4: Admin sidebar items verified\n";
        sleep(1);

        // Navigate through menu items
        $this->navigateToMenuPage('admin_profile.php');
        $this->verifyPageLoaded('Admin');
        echo " ✓ My Profile page accessible\n";
        sleep(2);

        $this->navigateToMenuPage('class_room.php');
        $this->verifyPageLoaded('Classroom');
        echo " ✓ Classroom page accessible\n";
        sleep(2);

        $this->navigateToMenuPage('grade.php');
        $this->verifyPageLoaded('Grade');
        echo " ✓ Grade page accessible\n";
        sleep(2);

        $this->navigateToMenuPage('subject.php');
        $this->verifyPageLoaded('Subject');
        echo " ✓ Subject page accessible\n";
        sleep(2);

        echo "✓ Test Case 5: Admin login and access validated\n";
    }

    public function testStudentLoginAndAccess(): void
    {
        echo "Running testStudentLoginAndAccess...\n";
        $this->loginAs('std1@gmail.com', 'Student12345');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard1.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();

        echo "✓ Test Case 6: Student dashboard loaded\n";

        // Verify sidebar items for student role
        $this->verifySidebarItems(['Dashboard', 'My Profile']);
        sleep(1);
        echo "✓ Test Case 7: Student sidebar items verified\n";
        sleep(1);

        // Navigate to my profile
        $this->navigateToMenuPage('my_profile.php');
        $this->verifyPageLoaded('Profile');
        echo " ✓ My Profile page accessible\n";
        sleep(2);

        echo "✓ Test Case 8: Student login and access validated\n";
    }

    public function testTeacherLoginAndAccess(): void
    {
        echo "Running testTeacherLoginAndAccess...\n";
        $this->loginAs('t1@gmail.com', 'Teacher12345');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard2.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->waitForDashboardInfoBox('My STUDENT');

        echo "✓ Test Case 9: Teacher dashboard loaded\n";
        sleep(1);

        // Verify sidebar items for teacher role
        $this->verifySidebarItems(['Dashboard', 'My Profile', 'My Student']);
        echo "✓ Test Case 10: Teacher sidebar items verified\n";
        sleep(2);

        // Navigate to my profile
        $this->navigateToMenuPage('teacher_profile2.php');
        $this->verifyPageLoaded('Profile');
        echo " ✓ My Profile page accessible\n";
        sleep(2);

        // Navigate to My Student
        $this->navigateToMenuPage('my_student.php');
        $this->verifyPageLoaded('Student');
        echo " ✓ My Student page accessible\n";
        sleep(2);

        echo "✓ Test Case 11: Teacher login and access validated\n";
    }

    public function testParentLoginAndAccess(): void
    {
        echo "Running testParentLoginAndAccess...\n";
        $this->loginAs('dad1@gmail.com', 'Parent12345');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard3.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();

        echo "✓ Test Case 12: Parent dashboard loaded\n";
        sleep(1);

        // Verify sidebar items for parent role
        $this->verifySidebarItems(['Dashboard', 'Profile']);
        echo "✓ Test Case 13: Parent sidebar items verified\n";
        sleep(2);

        // Navigate to parent profile via treeview
        $this->clickTreeviewLink('Profile', 'parents_profile.php');
        $this->verifyPageLoaded('Profile');
        echo " ✓ My Profile page accessible\n";
        sleep(2);

        echo "✓ Test Case 14: Parent login and access validated\n";
    }

    public function testSignOutReturnsToLogin(): void
    {
        echo "Running testSignOutReturnsToLogin...\n";
        $this->loginAs('admin@getprojects.org', 'Admin12345');

        $this->waitForSignOutLink();
        $this->clickSignOut();

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('email')));

        sleep(2);
        echo "✓ Test Case 15: Sign out returns to login form\n";
    }

    public function testResponsiveDesign(): void
    {
        echo "Running testResponsiveDesign...\n";
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        $sizes = [
            [375, 667],
            [768, 1024],
            [1920, 1080],
        ];

        foreach ($sizes as $size) {
            $this->driver->manage()->window()->setSize(new WebDriverDimension($size[0], $size[1]));
            sleep(1);
            assert(strlen($this->driver->getPageSource()) > 0, 'Login page should render at ' . $size[0] . 'x' . $size[1]);
        }

        sleep(2);
        echo "✓ Test Case 16: Responsive login page renders at mobile, tablet, desktop widths\n";
    }

    public function runAllTests(): void
    {
        echo "Starting SMS Selenium test suite...\n\n";

        $tests = [
            'testLoginPageDisplays',
            'testInvalidLogin',
            'testAdminLoginAndAccess',        
            'testStudentLoginAndAccess',
            'testTeacherLoginAndAccess',
            'testParentLoginAndAccess',
            'testSignOutReturnsToLogin',
            'testResponsiveDesign',
        ];

        foreach ($tests as $test) {
            try {
                $this->setUp();
                $this->$test();
                $this->tearDown();
                echo "\n";
            } catch (Exception $e) {
                echo "✗ $test failed: " . $e->getMessage() . "\n\n";
                $this->tearDown();
            }
        }
        sleep(2);
        echo "SMS Selenium test suite completed!\n";
    }
}

$testSuite = new SchoolManagementSystemTest();
$testSuite->runAllTests();
