<?php
# Selenium test suite for SMS – Semi-Automated
# Generated by Sivaranjei T., 2026, University of Colombo, Sri Lanka.
require_once __DIR__ . '/../../../vendor/autoload.php';

use Facebook\WebDriver\Chrome\ChromeOptions;
use Facebook\WebDriver\Remote\DesiredCapabilities;
use Facebook\WebDriver\Remote\RemoteWebDriver;
use Facebook\WebDriver\WebDriverBy;
use Facebook\WebDriver\WebDriverExpectedCondition;
use Facebook\WebDriver\WebDriverWait;
use Facebook\WebDriver\WebDriverDimension;

class SchoolManagementSystemTest
{
    private $driver;
    private $baseUrl = 'http://localhost/research/sms/SMS_Semi-Automated/';

    public function setUp(): void
    {
        $host = 'http://localhost:50843'; // Change this if ChromeDriver runs on another port

        $options = new ChromeOptions();
        $options->setBinary('C:\Program Files\Google\Chrome\Application\chrome.exe');
        $options->addArguments(['--no-sandbox', '--disable-dev-shm-usage', '--disable-gpu', '--window-size=1920,1080']);

        $capabilities = DesiredCapabilities::chrome();
        $capabilities->setCapability(ChromeOptions::CAPABILITY, $options);

        $this->driver = RemoteWebDriver::create($host, $capabilities);
        $this->driver->manage()->window()->maximize();
    }

    public function tearDown(): void
    {
        if ($this->driver) {
            try {
                $this->driver->quit();
            } catch (Exception $e) {
                // The browser may already have closed after a WebDriver failure.
            }
            $this->driver = null;
        }
    }

    private function waitForLoginModal(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('loginFrom')));
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('email')));
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id('password')));
        $wait->until(WebDriverExpectedCondition::elementToBeClickable(WebDriverBy::id('btnSubmit')));
    }

    private function clickElementWhenReady(WebDriverBy $locator): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::elementToBeClickable($locator));
        $element = $this->driver->findElement($locator);

        try {
            $element->click();
        } catch (Exception $e) {
            $this->driver->executeScript('arguments[0].click();', [$element]);
        }
    }

    private function loginAs(string $email, string $password, ?string $expectedDashboard = null): void
    {
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        $emailElement = $this->driver->findElement(WebDriverBy::id('email'));
        $passwordElement = $this->driver->findElement(WebDriverBy::id('password'));

        $emailElement->clear()->sendKeys($email);
        $passwordElement->clear()->sendKeys($password);

        sleep(2);
        $this->clickElementWhenReady(WebDriverBy::id('btnSubmit'));

        $this->waitForLoginResult();
        if ($expectedDashboard !== null) {
            $wait = new WebDriverWait($this->driver, 20);
            try {
                $wait->until(WebDriverExpectedCondition::urlContains($expectedDashboard));
            } catch (Exception $e) {
                throw new RuntimeException(
                    'Expected dashboard ' . $expectedDashboard . ' but reached ' . $this->driver->getCurrentURL()
                );
            }
        }
    }

    private function waitForSignOutLink(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::cssSelector('.dropdown.user.user-menu > a.dropdown-toggle')));
    }

    private function openUserMenu(): void
    {
        $this->clickElementWhenReady(WebDriverBy::cssSelector('.dropdown.user.user-menu > a.dropdown-toggle'));
    }

    private function clickSignOut(): void
    {
        $this->openUserMenu();
        sleep(2);
        $this->clickElementWhenReady(WebDriverBy::cssSelector('a[href="login.php"]'));
    }

    private function waitForLoginResult(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        try {
            $wait->until(function () {
                $url = $this->driver->getCurrentURL();
                return strpos($url, 'view/dashboard') !== false
                    || strpos($url, 'view/login.php') !== false;
            });
        } catch (Exception $e) {
            throw new RuntimeException(
                'Login did not redirect. Current URL: ' . $this->driver->getCurrentURL()
            );
        }
    }

    private function waitForDashboardHeading(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//section[contains(@class,'content-header')]//h1[contains(normalize-space(.),'Dashboard') or contains(normalize-space(.),'Dashboard')]")));
    }

    private function waitForDashboardInfoBox(string $text): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//span[contains(@class,'info-box-text') and normalize-space(text())='$text']")));
    }

    private function goToClassroomPage(): void
    {
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->clickElementWhenReady(WebDriverBy::cssSelector('a[href="class_room.php"]'));
        $this->waitForClassroomPage();
    }

    private function waitForClassroomPage(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/class_room.php'));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//h1[contains(normalize-space(.),'Classroom')]") ));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('example1')));
    }

    private function waitForClassroomRow(string $name): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]")));
    }

    private function waitForClassroomNoRow(string $name): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(function () use ($name) {
            $rows = $this->driver->findElements(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]"));
            return count($rows) === 0;
        });
    }

    private function clickEditClassroomByName(string $name): void
    {
        $this->clickElementWhenReady(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]//a[contains(normalize-space(.),'Edit')]"));
    }

    private function deleteClassroomByName(string $name): void
    {
        $this->clickElementWhenReady(WebDriverBy::xpath("//table[@id='example1']//tr[.//td[normalize-space(text())='$name']]//a[contains(@class,'confirm-delete')]"));
        $this->clickElementWhenReady(WebDriverBy::id('btnYes'));
        $this->waitForClassroomNoRow($name);
    }

    private function createUniqueClassroomName(): string
    {
        return 'CR_' . time() . '_' . rand(1000, 9999);
    }

    private function waitForModalVisible(string $modalId): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::visibilityOfElementLocated(WebDriverBy::id($modalId)));
    }

    private function waitForModalHidden(string $modalId): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::invisibilityOfElementLocated(WebDriverBy::id($modalId)));
    }

    private function verifySidebarItems(array $items): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        foreach ($items as $item) {
            $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(
                WebDriverBy::xpath("//span[contains(normalize-space(text()),'{$item}')]")
            ));
        }
    }

    private function navigateToMenuPage(string $pageLink): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::elementToBeClickable(WebDriverBy::cssSelector("a[href='{$pageLink}']")));
        $this->clickElementWhenReady(WebDriverBy::cssSelector("a[href='{$pageLink}']"));
        sleep(2);
    }

    private function verifyDashboardMenuPages(array $pages, string $dashboardPath): void
    {
        foreach ($pages as $pageLink => $pageTitle) {
            $this->navigateToMenuPage($pageLink);
            $this->verifyPageLoaded($pageTitle);
            echo "  ✓ {$pageTitle} page accessible\n";

            $this->returnToDashboard($dashboardPath);
            $this->waitForDashboardHeading();
        }
    }

    private function verifyTreeviewMenuPages(array $menus, string $dashboardPath): void
    {
        foreach ($menus as $menu) {
            $this->clickTreeviewLink($menu['group'], $menu['link']);
            $this->verifyPageLoaded($menu['title']);
            echo "  ✓ {$menu['title']} page accessible\n";

            $this->returnToDashboard($dashboardPath);
            $this->waitForDashboardHeading();
        }
    }

    private function returnToDashboard(string $dashboardPath): void
    {
        $dashboardFile = basename($dashboardPath);
        $this->clickElementWhenReady(WebDriverBy::cssSelector("a[href='{$dashboardFile}']"));
        (new WebDriverWait($this->driver, 20))->until(
            WebDriverExpectedCondition::urlContains($dashboardPath)
        );
    }

    private function verifyEmployeeCrudAccess(): void
    {
        $this->navigateToMenuPage('teacher.php');
        $this->verifyPageLoaded('Teacher');
        (new WebDriverWait($this->driver, 20))->until(
            WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('form1'))
        );
        echo "  ✓ Employee create form accessible\n";

        $this->returnToDashboard('view/dashboard.php');
        $this->waitForDashboardHeading();
        $this->openEmployeeListPage();
        $this->verifyPageLoaded('Teacher');
        (new WebDriverWait($this->driver, 20))->until(
            WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('example1'))
        );
        (new WebDriverWait($this->driver, 20))->until(
            WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::cssSelector('.confirm-delete'))
        );
        (new WebDriverWait($this->driver, 20))->until(
            WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::xpath("//a[contains(normalize-space(.),'Edit')]") )
        );
        echo "  ✓ Employee edit and delete controls accessible\n";
    }

    private function openEmployeeListPage(): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $link = WebDriverBy::cssSelector('a[href="all_teacher.php"]');
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated($link));
        $this->driver->executeScript('window.location.href = arguments[0];', ['all_teacher.php']);
        $wait->until(WebDriverExpectedCondition::urlContains('view/all_teacher.php'));
    }
    private function clickTreeviewLink(string $treeviewSpanText, string $submenuLink): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        // Find and click the treeview header
        $header = WebDriverBy::xpath("//span[normalize-space(text())='{$treeviewSpanText}']/parent::a");
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated($header));
        $this->driver->executeScript('arguments[0].click();', [$this->driver->findElement($header)]);
        sleep(1);
        // Then click the submenu link
        $submenu = WebDriverBy::cssSelector("a[href='{$submenuLink}']");
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated($submenu));
        $this->driver->executeScript('arguments[0].click();', [$this->driver->findElement($submenu)]);
        sleep(2);
    }
    private function verifyPageLoaded(string $pageTitle): void
    {
        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(
            WebDriverBy::xpath("//h1[contains(normalize-space(text()),'{$pageTitle}')] | //section[contains(@class,'content-header')]//h1")
        ));
    }

    public function testLoginPageDisplays(): void
    {
        echo "Running testLoginPageDisplays...\n";
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        sleep(2);
        echo "✓ Test Case 1: Login page and modal displayed\n";
    }

    public function testInvalidLogin(): void
    {
        echo "Running testInvalidLogin...\n";
        $this->loginAs('invalid@example.com', 'wrongpass');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/login.php'));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('email')));
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('login_error')));

        echo "✓ Test Case 2: Invalid login returns to login page with error feedback\n";

        sleep(2);
    }

    public function testAdminLoginAndAccess(): void
    {
        echo "Running testAdminLoginAndAccess...\n";
        $this->loginAs('admin@getprojects.org', 'Admin12345', 'view/dashboard.php');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->waitForDashboardInfoBox('Total Student');

        echo "✓ Test Case 3: Admin dashboard loaded\n";
        sleep(1);

         // Verify sidebar items for Admin role
        $this->verifySidebarItems(['Dashboard', 'My Profile', 'Classroom', 'Grade', 'Subject', 'Teacher', 'Student', 'Attendance', 'Exam']);
        sleep(1);
        echo "✓ Test Case 4: Admin sidebar items verified\n";
        sleep(1);

        $this->verifyDashboardMenuPages([
            'admin_profile.php' => 'Admin',
            'class_room.php' => 'Classroom',
            'grade.php' => 'Grade',
            'subject.php' => 'Subject',
            'subject_routing.php' => 'Subject Routing',
            'timetable.php' => 'Timetable',
            'student_payment.php' => 'Payment',
            'petty_cash.php' => 'Petty Cash',
        ], 'view/dashboard.php');

        $this->verifyTreeviewMenuPages([
            ['group' => 'Teacher', 'link' => 'teacher.php', 'title' => 'Teacher'],
            ['group' => 'Teacher', 'link' => 'all_teacher.php', 'title' => 'Teacher'],
            ['group' => 'Student', 'link' => 'student.php', 'title' => 'Student'],
            ['group' => 'Student', 'link' => 'all_student.php', 'title' => 'Student'],
            ['group' => 'Attendance', 'link' => 'add_attendance.php', 'title' => 'Attendance'],
            ['group' => 'Exam', 'link' => 'exam.php', 'title' => 'Exam'],
        ], 'view/dashboard.php');

        echo "✓ Test Case 5: Admin dashboard menu access validated\n";
    }

    public function testAdminEmployeeCrudAccess(): void
    {
        echo "Running testAdminEmployeeCrudAccess...\n";
        $this->loginAs('admin@getprojects.org', 'Admin12345', 'view/dashboard.php');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard.php'));
        $this->waitForDashboardHeading();
        $this->verifyEmployeeCrudAccess();

        echo "✓ Test Case 6: Admin employee CRUD access validated\n";
    }

    public function testTenantLoginAndAccess(): void
    {
        echo "Running testTenantLoginAndAccess...\n";
        $this->loginAs('std1@gmail.com', 'Student12345', 'view/dashboard1.php');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard1.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();

        echo "✓ Test Case 7: Tenant dashboard loaded\n";

        // Verify sidebar items for student role
        $this->verifySidebarItems(['Dashboard', 'My Profile']);
        sleep(1);
        echo "✓ Test Case 8: Tenant sidebar items verified\n";

        $this->verifyDashboardMenuPages([
            'my_profile.php' => 'Profile',
            'my_payments.php' => 'Payment',
        ], 'view/dashboard1.php');

        $this->verifyTreeviewMenuPages([
            ['group' => 'Teacher', 'link' => 'my_teacher.php', 'title' => 'Teacher'],
            ['group' => 'Teacher', 'link' => 'all_teacher1.php', 'title' => 'Teacher'],
            ['group' => 'Subject', 'link' => 'my_subject.php', 'title' => 'Subject'],
            ['group' => 'Subject', 'link' => 'all_subject1.php', 'title' => 'Subject'],
            ['group' => 'Timetable', 'link' => 'my_timetable.php', 'title' => 'Timetable'],
            ['group' => 'Timetable', 'link' => 'all_timetable1.php', 'title' => 'Timetable'],
            ['group' => 'Attendance', 'link' => 'my_attendance.php', 'title' => 'Attendance'],
            ['group' => 'Exam', 'link' => 'my_exam_marks.php', 'title' => 'Exam'],
        ], 'view/dashboard1.php');

        echo "✓ Test Case 9: Tenant login and access validated\n";
    }

    public function testEmployeeLoginAndAccess(): void
    {
        echo "Running testEmployeeLoginAndAccess...\n";
        $this->loginAs('t1@gmail.com', 'Teacher12345', 'view/dashboard2.php');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard2.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();
        $this->waitForDashboardInfoBox('My STUDENT');

        echo "✓ Test Case 10: Employee dashboard loaded\n";
        sleep(1);

        // Verify sidebar items for teacher role
        $this->verifySidebarItems(['Dashboard', 'My Profile', 'My Student', 'Subject', 'Timetable', 'Attendance', 'Exam', 'Friends', 'Events']);
        echo "✓ Test Case 11: Employee sidebar items verified\n";

        $this->verifyDashboardMenuPages([
            'teacher_profile2.php' => 'Profile',
            'my_student.php' => 'Student',
            'my_salary.php' => 'Salary',
            'my_petty_cash.php' => 'Petty Cash',
        ], 'view/dashboard2.php');

        $this->verifyTreeviewMenuPages([
            ['group' => 'Subject', 'link' => 'my_subject2.php', 'title' => 'Subject'],
            ['group' => 'Subject', 'link' => 'all_subject2.php', 'title' => 'Subject'],
            ['group' => 'Timetable', 'link' => 'my_timetable2.php', 'title' => 'Timetable'],
            ['group' => 'Timetable', 'link' => 'all_timetable2.php', 'title' => 'Timetable'],
            ['group' => 'Attendance', 'link' => 'my_attendance2.php', 'title' => 'Attendance'],
            ['group' => 'Exam', 'link' => 'my_student_exam_marks.php', 'title' => 'Exam'],
            ['group' => 'Exam', 'link' => 'exam_timetable2.php', 'title' => 'Exam'],
            ['group' => 'Friends', 'link' => 'add_friends2.php', 'title' => 'Friends'],
            ['group' => 'Events', 'link' => 'my_events2.php', 'title' => 'Events'],
        ], 'view/dashboard2.php');

        echo "✓ Test Case 12: Employee login and access validated\n";
    }

    public function testOwnerLoginAndAccess(): void
    {
        echo "Running testOwnerLoginAndAccess...\n";
        $this->loginAs('dad1@gmail.com', 'Parent12345', 'view/dashboard3.php');

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::urlContains('view/dashboard3.php'));
        $this->waitForSignOutLink();
        $this->waitForDashboardHeading();

        echo "✓ Test Case 13: Owner dashboard loaded\n";
        sleep(1);

        // Verify sidebar items for parent role
        $this->verifySidebarItems(['Dashboard', 'Profile', 'Teacher', 'Subject', 'Timetable', 'Attendance', 'My Son']);
        echo "✓ Test Case 14: Owner sidebar items verified\n";

        $this->verifyTreeviewMenuPages([
            ['group' => 'Profile', 'link' => 'parents_profile.php', 'title' => 'Profile'],
            ['group' => 'Profile', 'link' => 'my_sons_profile.php', 'title' => 'Profile'],
            ['group' => 'Teacher', 'link' => 'my_sons_teacher.php', 'title' => 'Teacher'],
            ['group' => 'Teacher', 'link' => 'all_teacher3.php', 'title' => 'Teacher'],
            ['group' => 'Subject', 'link' => 'my_sons_subject.php', 'title' => 'Subject'],
            ['group' => 'Subject', 'link' => 'all_subject3.php', 'title' => 'Subject'],
            ['group' => 'Timetable', 'link' => 'my_sons_timetable.php', 'title' => 'Timetable'],
            ['group' => 'Timetable', 'link' => 'all_timetable3.php', 'title' => 'Timetable'],
            ['group' => 'Attendance', 'link' => 'my_sons_attendance.php', 'title' => 'Attendance'],
            ['group' => 'Exam', 'link' => 'my_sons_exam_marks.php', 'title' => 'Exam'],
            ['group' => 'Exam', 'link' => 'my_sons_exam_timetable.php', 'title' => 'Exam'],
        ], 'view/dashboard3.php');

        echo "✓ Test Case 15: Owner login and access validated\n";
    }

    public function testSignOutReturnsToLogin(): void
    {
        echo "Running testSignOutReturnsToLogin...\n";
        $this->loginAs('admin@getprojects.org', 'Admin12345', 'view/dashboard.php');

        $this->waitForSignOutLink();
        $this->clickSignOut();

        $wait = new WebDriverWait($this->driver, 20);
        $wait->until(WebDriverExpectedCondition::presenceOfElementLocated(WebDriverBy::id('email')));

        sleep(2);
        echo "✓ Test Case 16: Sign out returns to login form\n";
    }

    public function testResponsiveDesign(): void
    {
        echo "Running testResponsiveDesign...\n";
        $this->driver->get($this->baseUrl . 'index.php');
        $this->waitForLoginModal();

        $sizes = [
            [375, 667],
            [768, 1024],
            [1920, 1080],
        ];

        foreach ($sizes as $size) {
            $this->driver->manage()->window()->setSize(new WebDriverDimension($size[0], $size[1]));
            sleep(1);
            assert(strlen($this->driver->getPageSource()) > 0, 'Login page should render at ' . $size[0] . 'x' . $size[1]);
        }

        sleep(2);
        echo "✓ Test Case 17: Responsive login page renders at mobile, tablet, desktop widths\n";
    }

    public function runAllTests(): void
    {
        echo "Starting SMS Selenium test suite...\n\n";

        $tests = [
            'testLoginPageDisplays',
            'testInvalidLogin',
            'testAdminLoginAndAccess',        
            'testAdminEmployeeCrudAccess',
            'testTenantLoginAndAccess',
            'testEmployeeLoginAndAccess',
            'testOwnerLoginAndAccess',
            'testSignOutReturnsToLogin',
            'testResponsiveDesign',
        ];

        foreach ($tests as $test) {
            try {
                $this->setUp();
                $this->$test();
                $this->tearDown();
                echo "\n";
            } catch (Exception $e) {
                $details = $e->getMessage();
                if ($details === '') {
                    $details = get_class($e);
                }
                if ($this->driver) {
                    try {
                        $details .= ' | URL: ' . $this->driver->getCurrentURL();
                    } catch (Exception $driverException) {
                        $details .= ' | Browser session unavailable';
                    }
                }
                echo "✗ $test failed: " . $details . "\n\n";
                $this->tearDown();
            }
        }
        sleep(2);
        echo "SMS Selenium test suite completed!\n";
    }
}

$testSuite = new SchoolManagementSystemTest();
$testSuite->runAllTests();
